[package]
name = "lifeshot-io"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
edition = "2018"

[dependencies]
ctrlc = "*"
geng = { git = "https://gitlab.com/kuviman/geng" }
serde = "*"
net = { path = "net" }
structopt = "*"
log = "*"
env_logger = "*"