[package]
name = "net"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
edition = "2018"

[dependencies]
geng = { git = "https://gitlab.com/kuviman/geng" }
ws = "*"
url = "*"
log = "*"
bincode = "*"